### ISSUE TITLE
Unable to get `apollo-query` to retrieve data

### ISSUE THREAD

**Issue by superchris** [apollo-elements/apollo-elements#218] opened 2021-12-30 01:09 UTC
## Package
﻿
`@apollo-elements/components`

## Description
Unable to get `apollo-query` to do anything

## Steps To Reproduce
clone this reproduction repo https://github.com/superchris/apollo-elements-test

1. `npm i`
1. `npm start:serve`

## Expected Behavior
The apollo-query element should display the query results from https://countries.trevorblades.com/

## Actual Behavior
Nothing happens

**Comment by bennypowers** [comment] 2021-12-30 07:39
Thanks for the issue @superchris. I've reproduced it and confirmed. The error appears to be a bug in [stampino](https://github.com/justinfagnani/stampino/), the library underlying apollo elements components' dynamic template support.

> Uncaught SyntaxError: import not found: _Σ     stampino.ts:7:8

I was able to work around this problem by adding this file:

`patches/stampino+0.6.2.patch`

```diff
diff --git a/node_modules/stampino/stampino.js b/node_modules/stampino/stampino.js
index 3021718..bf87669 100644
--- a/node_modules/stampino/stampino.js
+++ b/node_modules/stampino/stampino.js
@@ -1,7 +1,7 @@
 import { render as renderLit, nothing } from 'lit-html';
 import { parse, Parser, EvalAstFactory } from 'jexpr';
-import { _Σ } from 'lit-html/private-ssr-support.js';
-const { AttributePart, PropertyPart, BooleanAttributePart, EventPart } = _Σ;
+import { _$LH } from 'lit-html/private-ssr-support.js';
+const { AttributePart, PropertyPart, BooleanAttributePart, EventPart } = _$LH;
 const astFactory = new EvalAstFactory();
 const expressionCache = new Map();
 const toCamelCase = (s) => s.replace(/-(-|\w)/g, (_, p1) => p1.toUpperCase());
```

And then adding this script to package.json:

```json
"postinstall": "npx patch-package",
```

**Comment by bennypowers** [comment] 2021-12-30 07:40
See https://github.com/justinfagnani/stampino/pull/33

**Comment by superchris** [comment] 2021-12-30 15:59
Thanks @bennypowers, that worked like a champ! Feel free to close or leave open til the stampino bug is fixed, not sure which you would prefer.

**Comment by bennypowers** [comment] 2022-01-24 15:41
Closing since #220 pre-bundles it's own copy of stampino

**Closed by bennypowers** 2022-01-24 15:41 UTC
Labels: bug
